.TH APX 1 "2023-04-13" "apx" "User Manual"
.SH NAME
.RS 4
apx - Apx est un gestionnaire de paquet qui supporte de multiples sources, 
.PP
et permet de les installer dans un conteneur\&.
.RE
.SH SYNOPSIS
.RS 4
apx [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Apx est un gestionnaire de paquet qui supporte de multiples sources,
.PP
et permet de les installer dans un conteneur\&.
.RE
.SH OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SH APX COMMANDS
.RS 4
\fBautoremove\fP
.RS 4
Supprimer automatiquement les paquets inutilisés
.PP
.RE
\fBclean\fP
.RS 4
Nettoyer le cache du gestionnaire de packages apx
.PP
.RE
\fBenter\fP
.RS 4
Entrer dans le shell du conteneur
.PP
.RE
\fBexport\fP
.RS 4
Créer/Recréer un raccourci du programme sur le bureau
.PP
.RE
\fBinit\fP
.RS 4
Créer un conteneur
.PP
.RE
\fBinstall\fP
.RS 4
Installer des paquets à l'intérieur d'un conteneur\&.
.PP
.RE
\fBlist\fP
.RS 4
Liste des paquets installés\&.
.PP
.RE
\fBpurge\fP
.RS 4
Purger les paquets à l'intérieur d'un conteneur
.PP
.RE
\fBremove\fP
.RS 4
Retirer des paquets à l'intérieur d'un conteneur\&.
.PP
.RE
\fBrun\fP
.RS 4
Exécuter un programme dans un conteneur\&.
.PP
.RE
\fBsearch\fP
.RS 4
Recherche de paquets dans un conteneur\&.
.PP
.RE
\fBshow\fP
.RS 4
Afficher les détails d'un paquet
.PP
.RE
\fBunexport\fP
.RS 4
Désexporter/supprimer l'entrée du bureau d'un programme d'un conteneur
.PP
.RE
\fBupgrade\fP
.RS 4
Mettre à jour le système en installant/améliorant les paquets disponibles\&.
.PP
.RE
\fBupdate\fP
.RS 4
Mise à jour de la liste des paquets disponibles
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/apx/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH APX SUBCOMMANDS
.SH SUBCOMMAND AUTOREMOVE
.RS 4
Supprimer automatiquement les paquets inutilisés
.RE
.SS SYNOPSIS
.RS 4
\fBautoremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Supprimer automatiquement les paquets inutilisés
.RE
.SS OPTIONS
  -a, --all   Appliquer pour tous les conteneurs\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SH SUBCOMMAND CLEAN
.RS 4
Nettoyer le cache du gestionnaire de packages apx
.RE
.SS SYNOPSIS
.RS 4
\fBclean\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Nettoyer le cache du gestionnaire de paquet apx
.RE
.SS OPTIONS
  -a, --all   Appliquer pour tous les conteneurs\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SH SUBCOMMAND ENTER
.RS 4
Entrer dans le shell du conteneur
.RE
.SS SYNOPSIS
.RS 4
\fBenter\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Entrer dans le shell du conteneur
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SH SUBCOMMAND EXPORT
.RS 4
Créer/Recréer un raccourci du programme sur le bureau
.RE
.SS SYNOPSIS
.RS 4
\fBexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Créer/Recréer un raccourci du programme sur le bureau
.RE
.SS OPTIONS
      --bin   Exporter la commande binaire
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx export htop
.PP
apx export --bin fzf
.RE
.SH SUBCOMMAND INIT
.RS 4
Créer un conteneur
.RE
.SS SYNOPSIS
.RS 4
\fBinit\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Créer un conteneur
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx init
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Installer des paquets à l'intérieur d'un conteneur\&.
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Installer des paquets à l'intérieur d'un conteneur\&.
.RE
.SS OPTIONS
  -y, --assume-yes       Continuer sans confirmation manuelle
.PP
  -f, --fix-broken       Corriger les dépendances cassées avant l'installation
.PP
      --no-export        Ne pas créer de raccourci du programme sur le bureau après l'installation\&.
.PP
      --sideload         Installer un paquet depuis un fichier local\&.
.PP
      --allow-unfree     Autoriser les paquets avec des licences non libres
.PP
      --allow-insecure   Autoriser les paquets dont les vulnérabilités sont connues\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx install htop git
.PP
apx --nix install --allow-unfree vscode
.RE
.SH SUBCOMMAND LIST
.RS 4
Liste des paquets installés\&.
.RE
.SS SYNOPSIS
.RS 4
\fBlist\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Liste des paquets installés\&.
.RE
.SS OPTIONS
  -u, --upgradable   Afficher les paquets pouvant être mis à niveau
.PP
  -i, --installed    Afficher les paquets installés
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SH SUBCOMMAND PURGE
.RS 4
Purger les paquets à l'intérieur d'un conteneur
.RE
.SS SYNOPSIS
.RS 4
\fBpurge\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Purger les paquets à l'intérieur d'un conteneur
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx purge htop
.RE
.SH SUBCOMMAND REMOVE
.RS 4
Retirer des paquets à l'intérieur d'un conteneur\&.
.RE
.SS SYNOPSIS
.RS 4
\fBremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Retirer des paquets à l'intérieur d'un conteneur\&.
.RE
.SS OPTIONS
  -y, --assume-yes   Procéder sans confirmation manuelle\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx remove htop
.RE
.SH SUBCOMMAND RUN
.RS 4
Exécuter un programme dans un conteneur\&.
.RE
.SS SYNOPSIS
.RS 4
\fBrun\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Exécuter un programme dans un conteneur\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx run htop
.RE
.SH SUBCOMMAND SEARCH
.RS 4
Recherche de paquets dans un conteneur\&.
.RE
.SS SYNOPSIS
.RS 4
\fBsearch\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Recherche de paquets dans un conteneur\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx search neovim
.RE
.SH SUBCOMMAND SHOW
.RS 4
Afficher les détails d'un paquet
.RE
.SS SYNOPSIS
.RS 4
\fBshow\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Afficher les détails d'un paquet
.RE
.SS OPTIONS
  -i, --isinstalled   Ne renvoie que si le paquet est installé
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx show htop
.PP
apx show -i neovim
.RE
.SH SUBCOMMAND UNEXPORT
.RS 4
Désexporter/supprimer l'entrée du bureau d'un programme d'un conteneur
.RE
.SS SYNOPSIS
.RS 4
\fBunexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Désexporter/supprimer l'entrée du bureau d'un programme d'un conteneur\&.
.PP
Si l'option --bin est fournie, supprimer le lien vers le binaire du conteneur\&.
.RE
.SS OPTIONS
      --bin   Désexporter un binaire précédemment exporté\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx unexport code
.RE
.SH SUBCOMMAND UPGRADE
.RS 4
Mettre à jour le système en installant/améliorant les paquets disponibles\&.
.RE
.SS SYNOPSIS
.RS 4
\fBupgrade\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Mettre à jour le système en installant/améliorant les paquets disponibles\&.
.RE
.SS OPTIONS
  -a, --all          Appliquer pour tous les conteneurs\&.
.PP
  -y, --assume-yes   Procéder sans confirmation manuelle\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP
.SS EXAMPLES
.RS 4
apx upgrade
.RE
.SH SUBCOMMAND UPDATE
.RS 4
Mise à jour de la liste des paquets disponibles
.RE
.SS SYNOPSIS
.RS 4
\fBupdate\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Mise à jour de la liste des paquets disponible
.RE
.SS OPTIONS
  -a, --all          Appliquer pour tous les conteneurs\&.
.PP
  -y, --assume-yes   Procéder sans confirmation manuelle\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       Afficher une sortie plus détaillée
.PP
      --apt           Installer des paquets à partir du dépôt Ubuntu\&.
.PP
      --aur           Installer des paquets à partir de l'AUR (Arch User Repository)\&.
.PP
      --dnf           Installer des paquets du dépôt DNF (Dandified YUM) de Fedora\&.
.PP
      --apk           Installer des paquets du dépôt d'Alpine\&.
.PP
      --zypper        Installer des paquets du dépôt d'OpenSUSE\&.
.PP
      --xbps          Installer des paquets du dépôt Void (Linux)\&.
.PP
      --nix           Installer des paquets du dépôt Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Appliquer pour modifier le conteneur avec ce nom\&.
.PP

