#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

# Params
DEV_IMPORTS=true
SUBCOMMANDS="clean enter help init install list purge remove run search show update upgrade version"
CONTAINER_NAME="apx_managed"
VERSION="0.0.1"
APP_LABEL="◆"

# Imports
if [ "$DEV_IMPORTS" = true ]; then
    . ./utils/logger
    . ./utils/container
    for subcommand in $SUBCOMMANDS; do
        . ./subcommands/$subcommand
    done
else
    . /usr/share/apx/utils/logger
    . /usr/share/apx/utils/container
    for subcommand in $SUBCOMMANDS; do
        . /usr/share/apx/subcommands/$subcommand
    done
fi

# Exit if the script..
# ..distrobox is not installed
if ! which distrobox > /dev/null; then
    err "distrobox is not installed or not in PATH"
    exit 1
fi
# ..neither podman nor docker are installed
if ! which $(container_manager) > /dev/null; then
    err "Neither podman nor docker are installed"
    exit 1
fi
# ..was launched without arguments
if [ -z "$1" ]; then
    err "No arguments provided"
    exit 1
fi
# ..was launched as root
if [ "$(id -u)" -eq 0 ]; then
    err "This script must not be run as root"
    exit 1
fi
# ..is running inside a container
if [ -f /.dockerenv ] || [ -f /.containerenv ]; then
    err "This script must not be run inside a container"
    exit 1
fi
# ..was launched with an invalid subcommand
if ! echo "$SUBCOMMANDS" | grep -q "$1"; then
    err "Invalid operation $1"
    exit 1
fi
# ..the container does not exist
if ! container_exists && [ "$1" != "help" ] && [ "$1" != "version" ] && [ "$1" != "init" ]; then
    err "Container $CONTAINER_NAME does not exist. Use 'apx init' to create it"
    exit 1
fi

# Run the subcommand
subcommand="$1"
shift
apx_$subcommand "$@"
