#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

# Params
DEV_IMPORTS=true
SUBCOMMANDS="clean export unexport enter help init install list log purge remove run search show update upgrade version"
CONTAINER_NAME="apx_managed"
VERSION="0.0.7"
APP_LABEL="◆"
LOGS_DIR="/var/log/apx"

# Packagers must pre-configure apx placing a file named "packager-rules.cfg" in
# /etc/apx. This file must contain the following variables:
# - PKG_CONTAINER_IMAGE: the image to use for the container e.g. "archlinux:latest"
# - PKG_MANAGER_NEED_SUDO: if the package manager needs sudo to run
# - PKG_MANAGER_INTERFACE: the interface to use for the container e.g. "pacman"
#                          then place a file named "packager-manager-interface.cfg"
#                          in /etc/apx (see the example file "packager-manager-interface.cfg.example"
#                          whcih implements the pacman interface)

# Imports
if [ "$DEV_IMPORTS" = true ]; then
    . ./utils/logger
    . ./utils/spinner
    . ./utils/container
    . ./utils/pkg_interface
    . ./utils/almost
    for subcommand in $SUBCOMMANDS; do
        . ./subcommands/$subcommand
    done
else
    . /usr/share/apx/utils/logger
    . /usr/share/apx/utils/spinner
    . /usr/share/apx/utils/container
    . /usr/share/apx/utils/pkg_interface
    . /usr/share/apx/utils/almost
    for subcommand in $SUBCOMMANDS; do
        . /usr/share/apx/subcommands/$subcommand
    done
fi
if [ -f /etc/apx/packager-rules.cfg ]; then
    . /etc/apx/packager-rules.cfg
fi
if [ -f /etc/apx/packager-manager-interface.cfg ]; then
    . /etc/apx/packager-manager-interface.cfg
fi

# Exit if the script..
# ..distrobox is not installed
if ! which distrobox > /dev/null; then
    err "distrobox is not installed or not in PATH"
    exit 1
fi
# ..neither podman nor docker are installed
if [ "$1" != "--sys" ] && ! which $(container_manager)  > /dev/null; then
    err "Neither podman nor docker are installed"
    exit 1
fi
# ..was launched without arguments
if [ -z "$1" ]; then
    err "No arguments provided"
    exit 1
fi
# ..was launched as root
if [ "$(id -u)" -eq 0 ]; then
    err "This script must not be run as root"
    exit 1
fi
# ..is running inside a container
if [ -f /.dockerenv ] || [ -f /.containerenv ]; then
    err "This script must not be run inside a container"
    exit 1
fi
# ..was launched with an invalid subcommand
if [ "$1" != "--sys" ] && ! echo "$SUBCOMMANDS" | grep -q "$1"; then
    err "Invalid operation $1"
    exit 1
fi
# ..the container does not exist
if [ "$1" != "--sys" ] && ! container_exists && [ "$1" != "help" ] && [ "$1" != "version" ] && [ "$1" != "init" ]; then
    err "Container $CONTAINER_NAME does not exist. Use 'apx init' to create it"
    exit 1
fi

# Run the subcommand trough apt if --sys is provided, it also takes care of
# the immutable check, the system will be set as rw and restored as ro after
# the command is executed
if [ "$1" = "--sys" ]; then
    shift
    immutable=false
    if is_immutable; then
        almost enter rw
        immutable=true
    fi
    sudo apt "$@"
    if [ "$immutable" = true ]; then
        almost enter ro
    fi
    exit $?
fi

# Run the subcommand on the container
subcommand="$1"
shift
apx_$subcommand "$@"
