.TH APX 1 "2023-04-13" "apx" "User Manual"
.SH NAME
.RS 4
apx - Apx - это пакетный менеджер с поддержкой нескольких источников,
.PP
позволяющий вам устанавливать пакеты в управляемом контейнере\&.
.RE
.SH SYNOPSIS
.RS 4
apx [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Apx - это пакетный менеджер с поддержкой нескольких источников,
.PP
позволяющий вам устанавливать пакеты в управляемом контейнере\&.
.RE
.SH OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SH APX COMMANDS
.RS 4
\fBautoremove\fP
.RS 4
Автоматически удалить все неиспользуемые пакеты
.PP
.RE
\fBclean\fP
.RS 4
Очистить кэш пакетного менеджера apx
.PP
.RE
\fBenter\fP
.RS 4
Войти в окружение управляемого контейнера
.PP
.RE
\fBexport\fP
.RS 4
Экспортировать или пересоздать ярлык программы из управляемого контейнера
.PP
.RE
\fBinit\fP
.RS 4
Инициализировать управляемый контейнер
.PP
.RE
\fBinstall\fP
.RS 4
Установить пакеты внутри управляемого контейнера\&.
.PP
.RE
\fBlist\fP
.RS 4
Показать установленные пакеты\&.
.PP
.RE
\fBpurge\fP
.RS 4
Очистить пакеты в управляемом контейнере
.PP
.RE
\fBremove\fP
.RS 4
Удалить пакеты внутри управляемого контейнера\&.
.PP
.RE
\fBrun\fP
.RS 4
Запустить программу внутри управляемого контейнера\&.
.PP
.RE
\fBsearch\fP
.RS 4
Искать пакеты в управляемом контейнере\&.
.PP
.RE
\fBshow\fP
.RS 4
Показать подробности пакета
.PP
.RE
\fBunexport\fP
.RS 4
Деэкспортировать или удалить ярлык программы из управляемого контейнера
.PP
.RE
\fBupgrade\fP
.RS 4
Обновить систему установкой или обновлением доступных пакетов\&.
.PP
.RE
\fBupdate\fP
.RS 4
Обновить список доступных пакетов
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/apx/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH APX SUBCOMMANDS
.SH SUBCOMMAND AUTOREMOVE
.RS 4
Автоматически удалить все неиспользуемые пакеты
.RE
.SS SYNOPSIS
.RS 4
\fBautoremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Автоматически удалить все неиспользуемые пакеты
.RE
.SS OPTIONS
  -a, --all   Применить ко всем контейнерам\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SH SUBCOMMAND CLEAN
.RS 4
Очистить кэш пакетного менеджера apx
.RE
.SS SYNOPSIS
.RS 4
\fBclean\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Очистить кэш пакетного менеджера apx
.RE
.SS OPTIONS
  -a, --all   Применить ко всем контейнерам\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SH SUBCOMMAND ENTER
.RS 4
Войти в окружение управляемого контейнера
.RE
.SS SYNOPSIS
.RS 4
\fBenter\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Войти в окружение управляемого контейнера
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SH SUBCOMMAND EXPORT
.RS 4
Экспортировать или пересоздать ярлык программы из управляемого контейнера
.RE
.SS SYNOPSIS
.RS 4
\fBexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Экспортировать или пересоздать ярлык программы из управляемого контейнера
.RE
.SS OPTIONS
      --bin   Экспортировать команду бинарника
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx export htop
.PP
apx export --bin fzf
.RE
.SH SUBCOMMAND INIT
.RS 4
Инициализировать управляемый контейнер
.RE
.SS SYNOPSIS
.RS 4
\fBinit\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Инициализировать управляемый контейнер
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx init
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Установить пакеты внутри управляемого контейнера\&.
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Установить пакеты внутри управляемого контейнера\&.
.RE
.SS OPTIONS
  -y, --assume-yes       Продолжить без подтверждения вручную
.PP
  -f, --fix-broken       Исправить сломанные зависимости перед установкой
.PP
      --no-export        Не экспортировать ярлык после установки\&.
.PP
      --sideload         Установить пакет из локального файла\&.
.PP
      --allow-unfree     Разрешить пакеты с несвободными лицензиями
.PP
      --allow-insecure   Разрешить пакеты с известными уязвимостями\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx install htop git
.PP
apx --nix install --allow-unfree vscode
.RE
.SH SUBCOMMAND LIST
.RS 4
Показать установленные пакеты\&.
.RE
.SS SYNOPSIS
.RS 4
\fBlist\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Показать установленные пакеты\&.
.RE
.SS OPTIONS
  -u, --upgradable   Показать обновляемые пакеты
.PP
  -i, --installed    Показать установленные пакеты
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SH SUBCOMMAND PURGE
.RS 4
Очистить пакеты в управляемом контейнере
.RE
.SS SYNOPSIS
.RS 4
\fBpurge\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Очистить пакеты в управляемом контейнере
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx purge htop
.RE
.SH SUBCOMMAND REMOVE
.RS 4
Удалить пакеты внутри управляемого контейнера\&.
.RE
.SS SYNOPSIS
.RS 4
\fBremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Удалить пакеты внутри управляемого контейнера\&.
.RE
.SS OPTIONS
  -y, --assume-yes   Продолжить без подтверждения вручную\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx remove htop
.RE
.SH SUBCOMMAND RUN
.RS 4
Запустить программу внутри управляемого контейнера\&.
.RE
.SS SYNOPSIS
.RS 4
\fBrun\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Запустить программу внутри управляемого контейнера\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx run htop
.RE
.SH SUBCOMMAND SEARCH
.RS 4
Искать пакеты в управляемом контейнере\&.
.RE
.SS SYNOPSIS
.RS 4
\fBsearch\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Искать пакеты в управляемом контейнере\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx search neovim
.RE
.SH SUBCOMMAND SHOW
.RS 4
Показать подробности пакета
.RE
.SS SYNOPSIS
.RS 4
\fBshow\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Показать подробности пакета
.RE
.SS OPTIONS
  -i, --isinstalled   Возвращать только тогда, когда пакет установлен
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx show htop
.PP
apx show -i neovim
.RE
.SH SUBCOMMAND UNEXPORT
.RS 4
Деэкспортировать или удалить ярлык программы из управляемого контейнера
.RE
.SS SYNOPSIS
.RS 4
\fBunexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Деэкспортировать или удалить ярлык программы из управляемого контейнера\&.
.PP
Если есть флаг --bin, удалить ссылку на бинарник контейнера\&.
.RE
.SS OPTIONS
      --bin   Деэкспортировать ранее экспортированный бинарник\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx unexport code
.RE
.SH SUBCOMMAND UPGRADE
.RS 4
Обновить систему установкой или обновлением доступных пакетов\&.
.RE
.SS SYNOPSIS
.RS 4
\fBupgrade\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Обновить систему установкой или обновлением доступных пакетов\&.
.RE
.SS OPTIONS
  -a, --all          Применить ко всем контейнерам\&.
.PP
  -y, --assume-yes   Продолжить без подтверждения вручную\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP
.SS EXAMPLES
.RS 4
apx upgrade
.RE
.SH SUBCOMMAND UPDATE
.RS 4
Обновить список доступных пакетов
.RE
.SS SYNOPSIS
.RS 4
\fBupdate\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Обновить список доступных пакетов
.RE
.SS OPTIONS
  -a, --all          Применить ко всем контейнерам\&.
.PP
  -y, --assume-yes   Продолжить без подтверждения вручную\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       показать более подробный вывод
.PP
      --apt           Установка пакетов из репозитория Ubuntu\&.
.PP
      --aur           Установка пакетов из репозитория AUR (Arch User Repository)\&.
.PP
      --dnf           Установка пакетов из репозитория Fedora DNF (Dandified YUM)\&.
.PP
      --apk           Установка пакетов из репозитория Alpine\&.
.PP
      --zypper        Установка пакетов из репозитория OpenSUSE\&.
.PP
      --xbps          Установка пакетов из репозитория Void (Linux)\&.
.PP
      --nix           Установка пакетов из репозитория Nixpkgs (Nix packages)\&.
.PP
  -n, --name string   Применить к собственному контейнеру с этим названием\&.
.PP

