#!/bin/sh#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

apx_install() {
    container_exec sudo apt install "$@"
    if [ "$?" -ne 1 ]; then
        container_gen_desktop_entry "$@"
        info "New package(s) installed: $@"
    else
        err "Failed to install package(s): $@"
    fi
}