#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

apx_remove() {
    container_rm_desktop_entry "$@"
    container_exec sudo apt remove "$@"

    # the following logs are muted and only stored in the log file
    # this allows this command to be used in scripts without
    # polluting the output
    if [ "$?" -ne 1 ]; then
        _info "Package(s) removed: $@"
    else
        _err "Failed to remove package(s): $@"
    fi
}
