.TH APX 1 "2023-04-13" "apx" "User Manual"
.SH NAME
.RS 4
apx - Apx è un gestore di pacchetti con supporto per più fonti,
.PP
che consente di installare i pacchetti in un container gestito\&.
.RE
.SH SYNOPSIS
.RS 4
apx [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Apx è un gestore di pacchetti con supporto per più fonti,
.PP
che consente di installare i pacchetti in un container gestito\&.
.RE
.SH OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SH APX COMMANDS
.RS 4
\fBautoremove\fP
.RS 4
Rimuovi automaticamente tutti i pacchetti inutilizzati
.PP
.RE
\fBclean\fP
.RS 4
Pulisci la cache di apx
.PP
.RE
\fBenter\fP
.RS 4
Entra nella shell del container gestito
.PP
.RE
\fBexport\fP
.RS 4
Esporta/Ricrea la voce di un programma in un container gestito
.PP
.RE
\fBinit\fP
.RS 4
Inizializza un container gestito
.PP
.RE
\fBinstall\fP
.RS 4
Installa pacchetti nel container gestito\&.
.PP
.RE
\fBlist\fP
.RS 4
Elenca i pacchetti installati\&.
.PP
.RE
\fBpurge\fP
.RS 4
Elimina i pacchetti all'interno di un container gestito
.PP
.RE
\fBremove\fP
.RS 4
Rimuovi i pacchetti all'interno di un container gestito\&.
.PP
.RE
\fBrun\fP
.RS 4
Esegui un programma in un container gestito\&.
.PP
.RE
\fBsearch\fP
.RS 4
Cerca i pacchetti in un container gestito\&.
.PP
.RE
\fBshow\fP
.RS 4
Mostra i dettagli di un pacchetto
.PP
.RE
\fBunexport\fP
.RS 4
Rimuove la voce del desktop di un programma da un container gestito
.PP
.RE
\fBupgrade\fP
.RS 4
Aggiorna il sistema installando/aggiornando i pacchetti disponibili\&.
.PP
.RE
\fBupdate\fP
.RS 4
Aggiorna l'elenco dei pacchetti disponibili
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/apx/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH APX SUBCOMMANDS
.SH SUBCOMMAND AUTOREMOVE
.RS 4
Rimuovi automaticamente tutti i pacchetti inutilizzati
.RE
.SS SYNOPSIS
.RS 4
\fBautoremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Rimuovi automaticamente tutti i pacchetti inutilizzati
.RE
.SS OPTIONS
  -a, --all   Applica a tutti i container\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SH SUBCOMMAND CLEAN
.RS 4
Pulisci la cache di apx
.RE
.SS SYNOPSIS
.RS 4
\fBclean\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Pulisci la cache di apx
.RE
.SS OPTIONS
  -a, --all   Applica a tutti i container\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SH SUBCOMMAND ENTER
.RS 4
Entra nella shell del container gestito
.RE
.SS SYNOPSIS
.RS 4
\fBenter\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Entra nella shell del container gestito
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SH SUBCOMMAND EXPORT
.RS 4
Esporta/Ricrea la voce di un programma in un container gestito
.RE
.SS SYNOPSIS
.RS 4
\fBexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Esporta/Ricrea la voce di un programma in un container gestito
.RE
.SS OPTIONS
      --bin   Comando per esportare un programma binario
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx export htop
.PP
apx export --bin fzf
.RE
.SH SUBCOMMAND INIT
.RS 4
Inizializza un container gestito
.RE
.SS SYNOPSIS
.RS 4
\fBinit\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Inizializza un container gestito
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx init
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Installa pacchetti nel container gestito\&.
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Installa pacchetti nel container gestito\&.
.RE
.SS OPTIONS
  -y, --assume-yes       Procedi senza conferma manuale
.PP
  -f, --fix-broken       Correggi le dipendenze non funzionanti prima dell' installazione
.PP
      --no-export        Non esportare una voce del desktop dopo l'installazione\&.
.PP
      --sideload         Installa un pacchetto da un file locale\&.
.PP
      --allow-unfree     Consenti i pacchetti con licenze non gratuite
.PP
      --allow-insecure   Consenti i pacchetti con vulnerabilità note\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx install htop git
.PP
apx --nix install --allow-unfree vscode
.RE
.SH SUBCOMMAND LIST
.RS 4
Elenca i pacchetti installati\&.
.RE
.SS SYNOPSIS
.RS 4
\fBlist\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Elenca i pacchetti installati\&.
.RE
.SS OPTIONS
  -u, --upgradable   Mostra i pacchetti aggiornabili
.PP
  -i, --installed    Mostra i pacchetti installati
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SH SUBCOMMAND PURGE
.RS 4
Elimina i pacchetti all'interno di un container gestito
.RE
.SS SYNOPSIS
.RS 4
\fBpurge\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Elimina i pacchetti all'interno di un container gestito
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx purge htop
.RE
.SH SUBCOMMAND REMOVE
.RS 4
Rimuovi i pacchetti all'interno di un container gestito\&.
.RE
.SS SYNOPSIS
.RS 4
\fBremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Rimuovi i pacchetti all'interno di un container gestito\&.
.RE
.SS OPTIONS
  -y, --assume-yes   Procedi senza conferma manuale\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx remove htop
.RE
.SH SUBCOMMAND RUN
.RS 4
Esegui un programma in un container gestito\&.
.RE
.SS SYNOPSIS
.RS 4
\fBrun\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Esegui un programma in un container gestito\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx run htop
.RE
.SH SUBCOMMAND SEARCH
.RS 4
Cerca i pacchetti in un container gestito\&.
.RE
.SS SYNOPSIS
.RS 4
\fBsearch\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Cerca i pacchetti in un container gestito\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx search neovim
.RE
.SH SUBCOMMAND SHOW
.RS 4
Mostra i dettagli di un pacchetto
.RE
.SS SYNOPSIS
.RS 4
\fBshow\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Mostra i dettagli di un pacchetto
.RE
.SS OPTIONS
  -i, --isinstalled   Mostra solo se il pacchetto è installato
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx show htop
.PP
apx show -i neovim
.RE
.SH SUBCOMMAND UNEXPORT
.RS 4
Rimuove la voce del desktop di un programma da un container gestito
.RE
.SS SYNOPSIS
.RS 4
\fBunexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Rimuove la voce del desktop di un programma da un container gestito\&.
.PP
Se viene fornito il flag --bin, rimuove il collegamento al binario del container\&.
.RE
.SS OPTIONS
      --bin   Rimuovi un binario precedentemente esportato\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx unexport code
.RE
.SH SUBCOMMAND UPGRADE
.RS 4
Aggiorna il sistema installando/aggiornando i pacchetti disponibili\&.
.RE
.SS SYNOPSIS
.RS 4
\fBupgrade\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Aggiorna il sistema installando/aggiornando i pacchetti disponibili\&.
.RE
.SS OPTIONS
  -a, --all          Applica a tutti i container\&.
.PP
  -y, --assume-yes   Procedi senza conferma manuale\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP
.SS EXAMPLES
.RS 4
apx upgrade
.RE
.SH SUBCOMMAND UPDATE
.RS 4
Aggiorna l'elenco dei pacchetti disponibili
.RE
.SS SYNOPSIS
.RS 4
\fBupdate\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Aggiorna l'elenco dei pacchetti disponibili
.RE
.SS OPTIONS
  -a, --all          Applica a tutti i container\&.
.PP
  -y, --assume-yes   Procedi senza conferma manuale\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       mostra un output più dettagliato
.PP
      --apt           Installa i pacchetti dal repository di Ubuntu\&.
.PP
      --aur           Installa i pacchetti da AUR (Arch User Repository)\&.
.PP
      --dnf           Installa i pacchetti dal repository DNF (Dandified YUM) di Fedora\&.
.PP
      --apk           Installa i pacchetti dal repository di Alpine\&.
.PP
      --zypper        Installa i pacchetti dal repository di OpenSUSE\&.
.PP
      --xbps          Installa i pacchetti dal repository di Void (Linux)\&.
.PP
      --nix           Installa i pacchetti dal repository Nixpkgs (pacchetti Nix)\&.
.PP
  -n, --name string   Applica al container personalizzato con questo nome\&.
.PP

