#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

host_image() {
    echo $(lsb_release -is | tr '[:upper:]' '[:lower:]')":"$(lsb_release -rs)
    return 0
}

container_manager() {
    if which podman > /dev/null; then
        echo "podman"
    elif which docker > /dev/null; then
        echo "docker"
    else
        err "No container engine found. Please install Podman or Docker"
        exit 1
    fi
}

container_exists() {
    if $(container_manager) ps -a | grep -q "$CONTAINER_NAME"; then
        return 0
    else
        return 1
    fi
}

distrobox_version() {
    echo $(distrobox version | grep -oP '(?<=distrobox: ).*')
    return 0
}

container_exec() {
    distrobox enter "$CONTAINER_NAME" -- "$@"
}

container_create() {
    distrobox create --name "$CONTAINER_NAME" --image "$(host_image)" --yes --additional-flags --label=manager=apx
    distrobox generate-entry "$CONTAINER_NAME" --delete
    return $?
}

container_stop() {
    distrobox stop "$CONTAINER_NAME" --yes
    return $?
}

container_rm() {
    distrobox stop "$CONTAINER_NAME" --yes
    distrobox rm "$CONTAINER_NAME" --yes
    return $?
}

container_gen_desktop_entry() {
    container_exec distrobox-export --app "$1" --export-label "$APP_LABEL"
    if [ "$?" -ne 0 ]; then
        container_exec distrobox-export --app "$(echo "$1" | cut -d'-' -f1)" --export-label "$APP_LABEL"
    fi

    if [ "$?" -ne 0 ]; then
        warn "No desktop entry found for $1, nothing to export"
        exit 1
    fi
}

container_rm_desktop_entry() {
    container_exec distrobox-export --app "$1" --delete
    if [ "$?" -ne 0 ]; then
        container_exec distrobox-export --app "$(echo "$1" | cut -d'-' -f1)" --delete
    fi

    if [ "$?" -ne 0 ]; then
        warn "No desktop entry found for $1, nothing to delete"
        exit 1
    fi
}