#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

PREFIX="apx:"
PREFIX_INFO="${PREFIX}info: "
PREFIX_ERROR="${PREFIX}error: "
PREFIX_WARNING="${PREFIX}warning: "
FORMAT_INFO="\033[1;34m"
FORMAT_WARN="\033[1;33m"
FORMAT_ERROR="\033[1;31m"
FORMAT_RESET="\033[0m"

current_log_file() {
    echo "$LOGS_DIR/$(date +%Y-%m-%d).log"
}

# functions to log messages without showing them on the terminal
_info() {
    echo "$(date +%Y-%m-%d\ %H:%M:%S) ${PREFIX_INFO}${@}" >> $(current_log_file)
}

_warn() {
    echo "$(date +%Y-%m-%d\ %H:%M:%S) ${PREFIX_WARNING}${@}" >> $(current_log_file)
}

_err() {
    echo "$(date +%Y-%m-%d\ %H:%M:%S) ${PREFIX_ERROR}${@}" >> $(current_log_file)
}

# functions to log messages and show them on the terminal
info() {
    echo "${FORMAT_INFO}${PREFIX_INFO}${FORMAT_RESET}${@}"
    _info "${@}"
}

warn() {
    echo "${FORMAT_WARN}${PREFIX_WARNING}${FORMAT_RESET}${@}"
    _warn "${@}"
}

err() {
    echo "${FORMAT_ERROR}${PREFIX_ERROR}${FORMAT_RESET}${@}"
    _err "${@}"
}