#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

PREFIX="apx:"
PREFIX_INFO="${PREFIX}info: "
PREFIX_ERROR="${PREFIX}error: "
PREFIX_WARNING="${PREFIX}warning: "

current_log_file() {
    echo "$LOGS_DIR/$(date +%Y-%m-%d).log"
}

# functions to log messages without showing them on the terminal
_info() {
    echo "$(date +%Y-%m-%d\ %H:%M:%S) ${PREFIX_INFO}${@}" >> $(current_log_file)
}

_warn() {
    echo "$(date +%Y-%m-%d\ %H:%M:%S) ${PREFIX_WARNING}${@}" >> $(current_log_file)
}

_err() {
    echo "$(date +%Y-%m-%d\ %H:%M:%S) ${PREFIX_ERROR}${@}" >> $(current_log_file)
}

# functions to log messages and show them on the terminal
info() {
    printf "$(tput setf 4)$(tput bold)$(tput setaf 4)${PREFIX_INFO}$(tput sgr0) ${@}"
    _info "${@}"
}

warn() {
    printf "$(tput setf 3)$(tput bold)$(tput setaf 3)${PREFIX_WARNING}$(tput sgr0) ${@}"
    _warn "${@}"
}

err() {
    printf "$(tput setf 1)$(tput bold)$(tput setaf 1)${PREFIX_ERROR}$(tput sgr0) ${@}"
    _err "${@}"
}