#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

spin() {
    if [ -z "$1" ]; then
        echo "No text to show"
        exit 1
    fi

    if [ -z "$2" ]; then
        echo "No command to spin"
        exit 1
    fi

    SPINNER_TEXT="$1"
    shift
    $@ > /dev/null 2>&1 &
    SPINNER_PID=$!
    SPINNER_CHARS="⠁ ⠃ ⠇ ⡇ ⠇ ⠃"

    while ps -p $SPINNER_PID >> /dev/null; do
        for SPINNER_CHAR in $SPINNER_CHARS; do
            printf "\r$SPINNER_CHAR $SPINNER_TEXT ..."
            sleep .1
        done
    done

    printf "\r\033[2K"

    wait $SPINNER_PID
    return $?
}
