#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

apx_enter() {
    distrobox enter "$CONTAINER_NAME"

    if [ "$?" -ne 1 ]; then
        info "You are now outside the container"
    else
        err "Failed to enter container, it might be corrupted, try to re-init it using 'apx init'"
    fi
}
