#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

apx_init() {
    PROCEED="y"
    ALREADY_EXISTS=false

    if container_exists; then
        ALREADY_EXISTS=true
        warn "Container already exists. Do you want to re-initialize it?\ 
This operation will remove everything, of course your files as well. [y/N] "
        read -r PROCEED
        PROCEED=$(echo "$PROCEED" | tr '[:upper:]' '[:lower:]')
    fi

    if [ "$PROCEED" = "y" ]; then
        if [ "$ALREADY_EXISTS" = true ]; then
            container_rm
        fi
    else
        return 0
    fi

    container_create
}
