#!/bin/sh
# License: GPLv3
# Authors:
#   Mirko Brombin <send@mirko.pm>
# Copyright: 2022
# Description: Apx is a wrapper around apt to make it works inside a container
#   from outside, directly on the host.

apx_purge() {
    pkg_manager_subcommand="$(get_subcommand purge)"
    if [ -n "$pkg_manager_subcommand" ]; then
        container_exec $pkg_manager_subcommand "$@"
    else
        container_exec sudo apt purge "$@"
    fi

    # the following logs are muted and only stored in the log file
    # this allows this command to be used in scripts without
    # polluting the output
    if [ "$?" -eq 0 ]; then
        _info "Purge completed"
    else
        _err "Failed to purge"
    fi
}