.TH APX 1 "2024-01-21" "apx" "User Manual"
.SH NAME
.RS 4
apx - Apx is a package manager with support for multiple sources, allowing you to install packages in subsystems\&.
.RE
.SH SYNOPSIS
.RS 4
apx [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Apx is a package manager with support for multiple sources, allowing you to install packages in subsystems\&.
.RE
.SH OPTIONS
.SH APX COMMANDS
.RS 4
\fBstacks\fP
.RS 4
Work with the stacks that are available in apx\&.
.PP
.RE
\fBsubsystems\fP
.RS 4
Work with the subsystems that are available in apx\&.
.PP
.RE
\fBpkgmanagers\fP
.RS 4
Work with the package managers that are available in apx\&.
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/apx/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH APX SUBCOMMANDS
.SH SUBCOMMAND STACKS
.RS 4
Work with the stacks that are available in apx\&.
.RE
.SS SYNOPSIS
.RS 4
\fBstacks\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Work with the stacks that are available in apx\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SH LIST
.RS 4
List all available stacks\&.
.PP
.RE
.SH SHOW
.RS 4
Show information about the specified stack\&.
.PP
.RE
.SH NEW
.RS 4
Create a new stack\&.
.PP
.RE
.SH UPDATE
.RS 4
Update the specified stack\&.
.PP
.RE
.SH RM
.RS 4
Remove the specified stack\&.
.PP
.RE
.SH EXPORT
.RS 4
Export the specified stack\&.
.PP
.RE
.SH IMPORT
.RS 4
Import the specified stack\&.
.PP
.RE
.SH SUBCOMMAND SUBSYSTEMS
.RS 4
Work with the subsystems that are available in apx\&.
.RE
.SS SYNOPSIS
.RS 4
\fBsubsystems\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Work with the subsystems that are available in apx\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SH LIST
.RS 4
List all available subsystems\&.
.PP
.RE
.SH NEW
.RS 4
Create a new subsystem\&.
.PP
.RE
.SH RM
.RS 4
Remove the specified subsystem\&.
.PP
.RE
.SH RESET
.RS 4
Reset the specified subsystem\&.
.PP
.RE
.SH SUBCOMMAND PKGMANAGERS
.RS 4
Work with the package managers that are available in apx\&.
.RE
.SS SYNOPSIS
.RS 4
\fBpkgmanagers\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Work with the package managers that are available in apx\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SH LIST
.RS 4
List all available package managers\&.
.PP
.RE
.SH SHOW
.RS 4
Show information about the specified package manager\&.
.PP
.RE
.SH NEW
.RS 4
Create a new package manager\&.
.PP
.RE
.SH RM
.RS 4
Remove the specified package manager\&.
.PP
.RE
.SH EXPORT
.RS 4
Export the specified package manager\&.
.PP
.RE
.SH IMPORT
.RS 4
Import the specified package manager\&.
.PP
.RE
.SH UPDATE
.RS 4
Update the specified package manager\&.
.PP
.RE
