.TH ROOT 1 "2026-01-14" "root" ""
.SH SUBCOMMAND ROOT
.RS 4
.RE
.SH SUBCOMMAND STACKS
.RS 4
Manage stacks
.RE
.SH SUBCOMMAND UPDATE
.RS 4
Update a stack
.RE
.SH SUBCOMMAND RM
.RS 4
Remove a stack
.RE
.SH SUBCOMMAND EXPORT
.RS 4
Export a stack
.RE
.SH SUBCOMMAND IMPORT
.RS 4
Import a stack
.RE
.SH SUBCOMMAND LIST
.RS 4
List all stacks
.RE
.SH SUBCOMMAND SHOW
.RS 4
Show details of a stack
.RE
.SH SUBCOMMAND NEW
.RS 4
Create a new stack
.RE
.SH SUBCOMMAND SUBSYSTEMS
.RS 4
Manage subsystems
.RE
.SH SUBCOMMAND RESET
.RS 4
Reset a subsystem
.RE
.SH SUBCOMMAND LIST
.RS 4
List all subsystems
.RE
.SH SUBCOMMAND NEW
.RS 4
Create a new subsystem
.RE
.SH SUBCOMMAND RM
.RS 4
Remove a subsystem
.RE
.SH SUBCOMMAND PKGMANAGERS
.RS 4
Manage package managers
.RE
.SH SUBCOMMAND IMPORT
.RS 4
Import a package manager
.RE
.SH SUBCOMMAND UPDATE
.RS 4
Update a package manager
.RE
.SH SUBCOMMAND LIST
.RS 4
List all package managers
.RE
.SH SUBCOMMAND SHOW
.RS 4
Show details of a package manager
.RE
.SH SUBCOMMAND NEW
.RS 4
Create a new package manager
.RE
.SH SUBCOMMAND RM
.RS 4
Remove a package manager
.RE
.SH SUBCOMMAND EXPORT
.RS 4
Export a package manager
.RE

