.TH APX 1 "2023-02-13" "apx" "User Manual"
.SH NAME
.RS 4
apx - Apx är en pakethanterare med stöd för flera källor,
.PP
så att du kan installera paket i en hanterad behållare\&.
.RE
.SH SYNOPSIS
.RS 4
apx [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Apx är en pakethanterare med stöd för flera källor,
.PP
så att du kan installera paket i en hanterad behållare\&.
.RE
.SH OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SH APX COMMANDS
.RS 4
\fBautoremove\fP
.RS 4
Ta bort alla oanvända paket automatiskt
.PP
.RE
\fBclean\fP
.RS 4
Rensa apx-pakethanterarens cache
.PP
.RE
\fBenter\fP
.RS 4
Gå med i ett skal i den hanterade behållaren
.PP
.RE
\fBexport\fP
.RS 4
Exportera/Återskapa ett programs skrivbordspost från en hanterad behållare
.PP
.RE
\fBinit\fP
.RS 4
Initiera en hanterad behållare
.PP
.RE
\fBinstall\fP
.RS 4
Installera paket i en hanterad behållare\&.
.PP
.RE
\fBlist\fP
.RS 4
Lista installerade paket\&.
.PP
.RE
\fBpurge\fP
.RS 4
Rensa paket inuti en hanterad behållare
.PP
.RE
\fBremove\fP
.RS 4
Ta bort paket inuti en hanterad behållare\&.
.PP
.RE
\fBrun\fP
.RS 4
Kör ett program inuti en hanterad behållare\&.
.PP
.RE
\fBsearch\fP
.RS 4
Sök efter paket i en hanterad behållare\&.
.PP
.RE
\fBshow\fP
.RS 4
Visa detaljer om ett paket
.PP
.RE
\fBunexport\fP
.RS 4
Avexportera/ta bort ett programs skrivbordspost från en hanterad behållare
.PP
.RE
\fBupgrade\fP
.RS 4
Uppgradera systemet genom att installera/uppgradera tillgängliga paket\&.
.PP
.RE
\fBupdate\fP
.RS 4
Uppdatera listan över tillgängliga paket
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/apx/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH APX SUBCOMMANDS
.SH SUBCOMMAND AUTOREMOVE
.RS 4
Ta bort alla oanvända paket automatiskt
.RE
.SS SYNOPSIS
.RS 4
\fBautoremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Ta bort alla oanvända paket automatiskt
.RE
.SS OPTIONS
  -a, --all   Verkställ för alla containrar\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SH SUBCOMMAND CLEAN
.RS 4
Rensa apx-pakethanterarens cache
.RE
.SS SYNOPSIS
.RS 4
\fBclean\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Rensa apx-pakethanterarens cache
.RE
.SS OPTIONS
  -a, --all   Verkställ för alla containrar\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SH SUBCOMMAND ENTER
.RS 4
Gå med i ett skal i den hanterade behållaren
.RE
.SS SYNOPSIS
.RS 4
\fBenter\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Gå med i ett skal i den hanterade behållaren
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SH SUBCOMMAND EXPORT
.RS 4
Exportera/Återskapa ett programs skrivbordspost från en hanterad behållare
.RE
.SS SYNOPSIS
.RS 4
\fBexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Exportera/Återskapa ett programs skrivbordspost från en hanterad behållare
.RE
.SS OPTIONS
      --bin   Exportera binärtkommando
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx export htop
.PP
apx export --bin fzf
.RE
.SH SUBCOMMAND INIT
.RS 4
Initiera en hanterad behållare
.RE
.SS SYNOPSIS
.RS 4
\fBinit\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Initiera en hanterad behållare
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx init
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Installera paket i en hanterad behållare\&.
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Installera paket i en hanterad behållare\&.
.RE
.SS OPTIONS
  -y, --assume-yes     Fortsätt utan manuell bekräftelse
.PP
  -f, --fix-broken     Åtgärda trasiga beroenden innan du installerar
.PP
      --no-export      Exportera inte en skrivbordspost efter installationen\&.
.PP
      --sideload       Installera ett paket från en lokal fil\&.
.PP
      --allow-unfree   Tillåt paket med ofria licenser
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx install htop git
.RE
.SH SUBCOMMAND LIST
.RS 4
Lista installerade paket\&.
.RE
.SS SYNOPSIS
.RS 4
\fBlist\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Lista installerade paket\&.
.RE
.SS OPTIONS
  -u, --upgradable   Visa uppgraderingsbara paket
.PP
  -i, --installed    Visa installerade paket
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SH SUBCOMMAND PURGE
.RS 4
Rensa paket inuti en hanterad behållare
.RE
.SS SYNOPSIS
.RS 4
\fBpurge\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Rensa paket inuti en hanterad behållare
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx purge htop
.RE
.SH SUBCOMMAND REMOVE
.RS 4
Ta bort paket inuti en hanterad behållare\&.
.RE
.SS SYNOPSIS
.RS 4
\fBremove\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Ta bort paket inuti en hanterad behållare\&.
.RE
.SS OPTIONS
  -y, --assume-yes   Fortsätt utan manuell bekräftelse\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx remove htop
.RE
.SH SUBCOMMAND RUN
.RS 4
Kör ett program inuti en hanterad behållare\&.
.RE
.SS SYNOPSIS
.RS 4
\fBrun\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Kör ett program inuti en hanterad behållare\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx run htop
.RE
.SH SUBCOMMAND SEARCH
.RS 4
Sök efter paket i en hanterad behållare\&.
.RE
.SS SYNOPSIS
.RS 4
\fBsearch\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Sök efter paket i en hanterad behållare\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx search neovim
.RE
.SH SUBCOMMAND SHOW
.RS 4
Visa detaljer om ett paket
.RE
.SS SYNOPSIS
.RS 4
\fBshow\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Visa detaljer om ett paket
.RE
.SS OPTIONS
  -i, --isinstalled   Returnera endast om paketet är installerat
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx show htop
.PP
apx show -i neovim
.RE
.SH SUBCOMMAND UNEXPORT
.RS 4
Avexportera/ta bort ett programs skrivbordspost från en hanterad behållare
.RE
.SS SYNOPSIS
.RS 4
\fBunexport\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Avexportera/ta bort ett programs skrivbordspost från en hanterad behållare\&.
.PP
Om --bin-flaggan tillhandahålls, ta bort länken till binär container\&.
.RE
.SS OPTIONS
      --bin   Avexportera en tidigare exporterad binär fil\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx unexport code
.RE
.SH SUBCOMMAND UPGRADE
.RS 4
Uppgradera systemet genom att installera/uppgradera tillgängliga paket\&.
.RE
.SS SYNOPSIS
.RS 4
\fBupgrade\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Uppdatera listan över tillgängliga paket
.RE
.SS OPTIONS
  -a, --all          Verkställ för alla containrar\&.
.PP
  -y, --assume-yes   Fortsätt utan manuell bekräftelse\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP
.SS EXAMPLES
.RS 4
apx upgrade
.RE
.SH SUBCOMMAND UPDATE
.RS 4
Uppdatera listan över tillgängliga paket
.RE
.SS SYNOPSIS
.RS 4
\fBupdate\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Uppdatera listan över tillgängliga paket
.RE
.SS OPTIONS
  -a, --all          Verkställ för alla containrar\&.
.PP
  -y, --assume-yes   Fortsätt utan manuell bekräftelse\&.
.PP
.SS GLOBAL OPTIONS
  -v, --verbose       visa mer detaljerad utdata
.PP
      --apt           Installera paket från Ubuntu arkiv\&.
.PP
      --aur           Installera paket från the AUR (Arch User repository)\&.
.PP
      --dnf           Installera paket från Fedora's DNF (Dandified YUM) förråd\&.
.PP
      --apk            Installera paket från Alpine arkiv\&.
.PP
      --zypper        Installera paket från OpenSUSE förråd\&.
.PP
      --xbps          Installera paket från Void (Linux) arkiv\&.
.PP
      --nix           Installera paket från Nixpkgs (Nix paket) arkiv\&.
.PP
  -n, --name string   Applicera på anpassad behållare med detta namn\&.
.PP

